name: Build & Publish to Dynamis

on:
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get Tag Name
        run: |
          tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
          echo "tag=$tag" >> $GITHUB_ENV

          if [[ "$tag" == *"-test" ]]; then
            branch="testing"
            tag=$(echo $tag | sed 's/-test//')
          else
            branch="latest"
          fi

          echo "branch=$branch" >> $GITHUB_ENV
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Download Dalamud Latest
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore Project
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release RotationSolver/RotationSolver.csproj -p:AssemblyVersion=${{ env.tag }}

      - name: Publish Version
        uses: PunishXIV/dynamis-action@v1
        id: dynamis
        with:
          plugin_id: 44
          internal_name: 'RotationSolver'
          version_number: ${{ env.tag }}
          path: 'RotationSolver/bin/Release/RotationSolver/latest.zip'
          type: '${{ env.branch }}'
          dalamud_version: '9'
        env:
          PUBLISHER_KEY: ${{ secrets.PUBLISHER_KEY }}
